"""
Agent state definitions.

This module defines the state schema used by the LangGraph agent workflow.
The state tracks the conversation flow, tool usage, and intermediate results.
"""

from typing import Any, TypedDict


class AgentState(TypedDict, total=False):
    """
    State schema for the GraphRAG agent workflow.
    
    This TypedDict defines all the fields that flow through the agent graph.
    Each node in the graph can read from and write to these fields.
    
    Attributes:
        question: The user's input question to answer.
        context: Aggregated context from tool calls (vector search, graph queries).
        answer: The final answer generated by the LLM.
        intermediate_steps: List of intermediate results from tool calls.
        used_tools: Names of tools that were invoked.
        error: Any error message if processing failed.
        should_use_tools: Router decision - whether to call tools.
        retrieval_results: Raw results from hybrid retrieval.
    """
    
    # Input
    question: str
    
    # Retrieval context
    context: str | None
    retrieval_results: dict[str, Any] | None
    
    # Tool tracking
    intermediate_steps: list[dict[str, Any]]
    used_tools: list[str]
    
    # Routing
    should_use_tools: bool
    
    # Output
    answer: str | None
    error: str | None
    
    # Workflow tracking (for UI visualization)
    workflow_steps: list[dict[str, Any]]


def create_initial_state(question: str) -> AgentState:
    """
    Create an initial agent state from a user question.
    
    Args:
        question: The user's question to answer.
    
    Returns:
        Initialized AgentState ready for processing.
    """
    return AgentState(
        question=question,
        context=None,
        retrieval_results=None,
        intermediate_steps=[],
        used_tools=[],
        should_use_tools=True,  # Default to using tools
        answer=None,
        error=None,
        workflow_steps=[],  # Track workflow execution
    )


def get_state_summary(state: AgentState) -> dict[str, Any]:
    """
    Get a summary of the current agent state for debugging/logging.
    
    Args:
        state: Current agent state.
    
    Returns:
        Dictionary with key state information.
    """
    return {
        "question": state.get("question", "")[:100],
        "has_context": state.get("context") is not None,
        "context_length": len(state.get("context", "") or ""),
        "tools_used": state.get("used_tools", []),
        "num_steps": len(state.get("intermediate_steps", [])),
        "has_answer": state.get("answer") is not None,
        "has_error": state.get("error") is not None,
    }

